# Generated by Django 3.2.12 on 2025-04-15 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=100, unique=True)),
                ('phq9_score', models.IntegerField()),
                ('gad7_score', models.IntegerField()),
                ('mbi_score', models.IntegerField()),
                ('combined_report', models.TextField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
