# Generated by Django 3.2.12 on 2025-04-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussubmission',
            name='sector',
            field=models.CharField(default='Général', max_length=100),
        ),
    ]
