# Generated by Django 3.2.12 on 2025-04-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anonymoussubmission_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussubmission',
            name='has_quit',
            field=models.BooleanField(default=False),
        ),
    ]
